
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Детский_сад
{

using System;
    using System.Collections.Generic;
    
public partial class Attendance
{

    public int Id_visit { get; set; }

    public System.DateTime Date_visit { get; set; }

    public int Id_child { get; set; }

    public int Status_visit { get; set; }



    public virtual Children Children { get; set; }

}

}
