//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Детский_сад
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Id_employee { get; set; }
        public string Surname { get; set; }
        public string Names { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int Id_gender { get; set; }
        public int Id_position { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string Phone { get; set; }
        public string Login_user { get; set; }
        public int Password_user { get; set; }
        public int Id_role { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
