//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Детский_сад
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kinships
    {
        public int Id_kinship { get; set; }
        public int Id_parent { get; set; }
        public int Id_child { get; set; }
    
        public virtual Children Children { get; set; }
        public virtual Parents Parents { get; set; }
    }
}
