

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Детский_сад
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class KindergartenEntities : DbContext
{
    public KindergartenEntities()
        : base("name=KindergartenEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Attendance> Attendance { get; set; }

    public virtual DbSet<Children> Children { get; set; }

    public virtual DbSet<Distributions> Distributions { get; set; }

    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<Genders> Genders { get; set; }

    public virtual DbSet<Groups> Groups { get; set; }

    public virtual DbSet<Kinships> Kinships { get; set; }

    public virtual DbSet<Parents> Parents { get; set; }

    public virtual DbSet<Positions> Positions { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Sertificates> Sertificates { get; set; }

    public virtual DbSet<Types_group> Types_group { get; set; }

}

}

