//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Детский_сад
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sertificates
    {
        public int Id_sertificate { get; set; }
        public int Series { get; set; }
        public string Number { get; set; }
        public System.DateTime Date_issue { get; set; }
        public string Iddued { get; set; }
    
        public virtual Children Children { get; set; }
    }
}
